routes/web.php
<?php

use App\Http\Controllers\AplikasiController;
use App\Http\Controllers\BukuController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PinjamController;
use App\Http\Controllers\RakController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [AplikasiController::class, 'dashboard'])->name('dashboard')->middleware('auth');


Route::resource('/buku', BukuController::class)->middleware('auth');
Route::resource('/pinjam', PinjamController::class)->middleware('auth');
Route::resource('/kategori', KategoriController::class)->middleware('auth');
Route::resource('/rak', RakController::class)->middleware('auth');

app/Models/Rak.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rak extends Model
{
    use HasFactory;

    protected $table = 'tbl_rak';

    protected $guarded = ['id'];
}

app/Http/Controllers/RakController.php
<?php

namespace App\Http\Controllers;

use App\Models\Rak;
use Illuminate\Http\Request;

class RakController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ( $request->user()->role != 'ADMIN') {
            return redirect('/');
        }

        $rak = Rak::all();

        return view('rak.index', compact('rak'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'nama_rak'   => 'required',
        ]);

        $simpan['nama_rak'] =  $request['nama_rak'];

        Rak::create($simpan);

        return back()->with('hijau', 'Data Rak telah ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Rak  $rak
     * @return \Illuminate\Http\Response
     */
    public function show(Rak $rak)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Rak  $rak
     * @return \Illuminate\Http\Response
     */
    public function edit(Rak $rak)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Rak  $rak
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Rak $rak)
    {
        $this->validate($request,[
            'nama_rak'   => 'required',
        ]);

        $rak->update($request->all());

        return back()->with('hijau', 'Data Rak '.$rak->nama_rak.' telah diubah.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Rak  $rak
     * @return \Illuminate\Http\Response
     */
    public function destroy(Rak $rak)
    {
        Rak::find($rak->id)->delete();

        return back()->with('merah', 'Rak '.$rak->nama_rak.' Telah dihapus.');
    }
}

resources/views/rak/index.blade.php
@extends('template.template')

{{-- SUBMENU --}}
@section('sub-menu')

<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item active" aria-current="page"><span>Rak</span></li>
</ol>

@endsection

@section('rak')

data-active="true"

@endsection

{{-- CSS --}}
@section('css')

<style>
    .table>tbody>tr>td {
        color: #000000;
    }
</style>

@endsection

@section('content')

<!--  BEGIN CONTENT AREA  -->
<div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-top-spacing">

            <div class="col-xl-6 col-lg-6 col-sm-6 mb-3">

                {{-- menampilkan error validasi --}}
                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif

                @if ($message = Session::get('hijau'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ $message }}</strong>
                </div>
                @endif

                @if ($message = Session::get('merah'))
                <div class="alert alert-danger alert-block">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ $message }}</strong>
                </div>
                @endif


                <button type="button" class="btn btn-primary btn-sm mb-3" data-toggle="modal" data-target="#tambah">
                    Tambah rak
                </button>


                <div class="card shadow mb-3">
                    <div class="card-body">
                        <div class="table-responsive mb-4 mt-4">
                            <table id="datatables" class="table nowrap table-hover" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Nama rak</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                @php
                                $no = 1;
                                @endphp
                                <tbody>
                                    @foreach ($rak as $data)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $data['nama_rak'] }}</td>
                                        <td class="text-center">
                                            <button type="button" class="btn btn-warning btn-sm" data-toggle="modal"
                                                data-target="#edit{{ $data['id'] }}">
                                                Edit
                                            </button>

                                            @if(\App\Models\Buku::where('id_rak', $data['id'])->count() >= 1)
                                            <button type="button" class="btn btn-danger btn-sm" disabled>
                                                Hapus
                                            </button>
                                            @else
                                            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                                                data-target="#hapus{{ $data['id'] }}">
                                                Hapus
                                            </button>
                                            @endif
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    <div class="footer-wrapper">
        <div class="footer-section f-section-1">
            <p class="">Copyright © 2021 <a target="_blank" href="https://designreset.com">ALDHI</a>, Test OXY.</p>
        </div>
        <div class="footer-section f-section-2">
            <p class="">Coded with <a href="http://instagram.com/aldhi009" target="_blank" rel="noopener noreferrer"
                    class="text-primary">Aldhi</a></p>
        </div>
    </div>
</div>
<!--  END CONTENT AREA  -->


{{-- MODAL TAMBAH rak --}}
<div class="modal fade" id="tambah">
    <div class="modal-dialog">
        <form action="{{ route('rak.store') }}" method="post">
            @csrf
            @method('POST')
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Tambah rak</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        x
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="nama_rak">Nama rak</label>
                        <input type="text" name="nama_rak" id="nama_rak" class="form-control" required>
                    </div>

                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Batal</button>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
            </div>
        </form>
    </div>

</div>


{{-- EDIT BUKU  --}}
@foreach($rak as $datarak)

<div class="modal fade" id="edit{{ $datarak['id'] }}" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form action="{{ route('rak.update', $datarak['id']) }}" method="post">
            @csrf
            @method('PUT')
            <div class="modal-content">


                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit buku {{ $datarak['nama_rak'] }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        x
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="nama_rak">Nama rak</label>
                        <input type="text" name="nama_rak" id="nama_rak" class="form-control"
                            value="{{ $datarak['nama_rak'] }}" required>
                    </div>

                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Batal</button>
                    <button type="submit" class="btn btn-warning">Ubah</button>
                </div>
            </div>
        </form>
    </div>
</div>

@endforeach

{{-- MODAL HAPUS KARYAWAN --}}
@foreach($rak as $datarak)
<div class="modal fade" id="hapus{{ $datarak['id'] }}">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h5 class="modal-title">Hapus rak {{ $datarak['nama_rak'] }}</h6>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <h6>Data yang dihapus tidak akan bisa dikembalikan.</h6>
            </div>
            <form action="{{ route('rak.destroy', $datarak['id']) }}" method="post">
                @csrf
                @method('DELETE')
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal"><i class="flaticon-cancel-12"></i> Batal</button>
                    <button type="submit" class="btn btn-danger">Hapus</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endforeach


@endsection


@section('js')

<script>
    $('#datatables').DataTable({
        dom: '<"row"<"col-md-12"<"row"<"col-md-6"B><"col-md-6"f> > ><"col-md-12"rt> <"col-md-12"<"row"<"col-md-10"i><"col-md-2 mb-3"p>>> >',
        buttons: {
            buttons: [{
                    extend: 'copy',
                    className: 'btn',
                    footer: true
                },
                {
                    extend: 'csv',
                    className: 'btn',
                    footer: true
                },
                {
                    extend: 'excel',
                    className: 'btn',
                    footer: true
                },
                {
                    extend: 'print',
                    className: 'btn',
                    footer: true
                }
            ]
        },
        "oLanguage": {
            "oPaginate": {
                "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>',
                "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'
            },
            "sInfo": "Showing page _PAGE_ of _PAGES_",
            "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
            "sSearchPlaceholder": "Search...",
            "sLengthMenu": "Results :  _MENU_",
        },
        "stripeClasses": [],
        "lengthMenu": [
            [10, 25, 50, -1],
            [10, 25, 50, "All"]
        ],
        "pageLength": 10,
        "pagingType": "simple",

    });
</script>

@endsection